
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/bramvdbogaerde/go-scp"

[[constraint]]
  name = "github.com/BurntSushi/toml"

[[constraint]]
  name = "github.com/atrox/homedir"

[[constraint]]
  name = "github.com/otiai10/gosseract"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/axgle/mahonia"

[[constraint]]
  name = "github.com/djimenez/iconv-go"

[[constraint]]
  name = "golang.org/x/text"

[[constraint]]
  name = "cloud.google.com/go/translate"
